### ISSUE TITLE
Radio Thermostat CT80 Rev B1 V1.00 error updating in home assistant

### ISSUE THREAD

**Issue by robthebold** [mhrivnak/radiotherm#34] opened 2018-04-22 01:42 UTC
(I believe this is not _exactly_ the same as #26 -- although the result is similar -- since the error message isn't quite the same.
 Apologies if it's a dup.)

When I add the radio thermostat component to my home assistant configuration, HA tries to add my device but fails and puts this error in the log:

`2018-04-21 10:41:14 ERROR (MainThread) [homeassistant.components.climate] radiotherm: Error on device update!                                      
Traceback (most recent call last):                                                                                                                 
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity                                 
    await entity.async_device_update(warning=False)                                                                                                
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update                                        
    yield from self.hass.async_add_job(self.update)                                                                                                
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                                                          
    result = self.fn(*self.args, **self.kwargs)                                                                                                    
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/radiotherm.py", line 237, in update                                      
    self._name = self.device.name['raw']                                                                                                           
AttributeError: 'NoneType' object has no attribute 'name'                                                                                          
2018-04-21 10:41:44 WARNING (SyncWorker_2) [netdisco.ssdp] Error fetching description at http://[fe80::d4e2:6588:1d90:ba8a]:6544/getDeviceDesc
`

Like in #26, I believe this may be related to the Rev no. of the device.

**Comment by craftyguy** [comment] 2018-04-22 03:07
It seems like radiotherm is not able to connect to your device. This is curious because the CT80 B1 v1.00 [is supported](https://github.com/mhrivnak/radiotherm/blob/master/radiotherm/__init__.py#L12) by radiotherm.

Are you able to run radiotherm from a python console? (i.e. reproduce this error by cloning this project, and running it with python following the readme) If so, there's an experiment that might be helpful in determining what might be wrong.

**Comment by robthebold** [comment] 2018-04-22 23:52
Here's what I get when I try radiotherm from python console on my desktop (which is on the same network as the thermostat and can ping it successfully) following the readme.rst instructions:

>>> import radiotherm
>>> tstat = radiotherm.get_thermostat()
>>> tstat.temp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'temp'
>>> tstat.mode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'mode'


BTW, the run-tests script passed all tests.

**Comment by TD22057** [comment] 2018-04-24 03:52
Try running this (use the actual IP address of your thermostat)
```
import radiotherm 
tstat = radiotherm.CommonThermostat( "192.168.1.10" )
print( tstat.model )
```

**Comment by robthebold** [comment] 2018-04-24 13:55
Ok, I gave it a try . . .

```
import radiotherm
tstat=radiotherm.CommonThermostat( "192.168.2.155")
print(tstat.model)
{'raw': u'CT80 Rev B1 V1.08'}

```

Additionally, the temp and mode methods now return data.

```
tstat.temp
{'raw': 68.0}
tstat.mode
{'raw': 1, 'human': 'Normal'}
```

**Comment by trisk** [comment] 2018-06-22 04:10
The version specific subclassing has been a real limitation for compatibility and is also largely unnecessary; I've been meaning to implement a proper class heirarchy with unknown models falling back to `CommonThermostat`.

**Comment by TD22057** [comment] 2018-06-22 15:54
Another think to consider in a fix for this is that the thermostats aren't very reliable.  At least for home assistant, it would be better to just use the common thermostat and not require a connection to be valid at start up.  Right now, if a the library can't connect to the thermostat, it fails and will never be available in home assistant which is annoying.  I think this is mostly a code change on the home assistant end but being able to create the thermostat class (probably common thermostat) w/o a valid connection is important.  Most of the time, the connection will be available later so it's not normally a big deal if it's not there at construction time.

**Comment by JerryWorkman** [comment] 2018-06-23 16:48
I created a pull request on Nov 5, 2016 that fixes this problem. It was
ignored.

As I recall I also added caching which was sorely needed.

https://github.com/JerryWorkman/radiotherm

**Comment by craftyguy** [comment] 2018-06-23 17:04
> I created a pull request on Nov 5, 2016 that fixes this problem. It was
ignored.

You did? I don't see any opened or closed PRs in this project from you:

https://github.com/mhrivnak/radiotherm/pulls?q=is%3Apr+is%3Aclosed

Feel free to re-submit it and I'll take a look.

**Comment by JerryWorkman** [comment] 2018-06-23 20:21
See my issue post here: https://github.com/mhrivnak/radiotherm/issues/14

It's been so long I'll need to diff/clone/pull all over.

**Comment by craftyguy** [comment] 2018-06-23 21:39
Ah, an issue, not a pull request. Yea if you have something to submit in a pull request, I'd be happy to review/merge it :)

If not, I can take a look at your branch later on when I have time and come up with a patch that will apply to the current codebase.

**Comment by craftyguy** [comment] 2018-06-28 02:28
Can you try with #38 ? This adds support for thermostats that are not explicitly defined in this project, with basic functionality. In your case it should enable functionality that all CT80 devices, regardless of rev and version, support. But since I don't have your device, it would be awesome to get a confirmation that this branch works before I merge it!

Special thanks to @JerryWorkman for his PR :+1:

**Comment by JerryWorkman** [comment] 2018-06-28 17:39
I have since replaced my Radiotherm.

**Comment by craftyguy** [comment] 2018-07-27 19:54
This should be resolved now. Closing issue, but please re-open if someone continues to experience this after testing the latest in master branch.

**Closed by craftyguy** 2018-07-27 19:54 UTC
